openapi: 3.0.0
info:
  title: Consellor App API
  description: An API created using node.js to handle operations helping people to connect with counsellors
  version: 1.0.1
  contact:
    email: abhishek1sharma14.1998@gmail.com

servers:
  - url: "{protocol}://localhost:8000/api/{version}"
    description: Local host initial URL
    variables:
      version:
        enum:
          - v1
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /signup:
    post:
      tags:
        - User Related Operations
      summary: User Can Signup using this path
      consumes:
        - application/json
      producers:
        - application/json
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                dob:
                  type: string
                  format: date
                qualification:
                  type: string
                aboutme:
                  type: string
                phno:
                  type: string
                role:
                  type: string
                photo:
                  type: string
                  format: binary
      responses:
        "200":
          description: All Good
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    type: object
                    properties:
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string
                      _id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      dob:
                        type: string
                        format: date
                      qualification:
                        type: string
                      aboutme:
                        type: string
                      phno:
                        type: number
                      role:
                        type: string
                      createdAt:
                        type: string
                        format: date
                      updatedAt:
                        type: string
                        format: date
                      __v:
                        type: number

  /login:
    post:
      tags:
        - User Related Operations
      summary: User Can Login using this path
      consumes:
        - application/json
      producers:
        - application/json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        "200":
          description: All Good
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    type: object
                    properties:
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string
                      _id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      dob:
                        type: string
                        format: date
                      qualification:
                        type: string
                      aboutme:
                        type: string
                      phno:
                        type: number
                      role:
                        type: string
                      createdAt:
                        type: string
                        format: date
                      updatedAt:
                        type: string
                        format: date
                      __v:
                        type: number

  /logout:
    get:
      tags:
        - User Related Operations
      summary: Logout User
      responses:
        "200":
          description: All Good
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /getuser:
    get:
      tags:
        - User Related Operations
      summary: Get User Details based on the cookie token. User first need to Login to get success response.
      responses:
        "200":
          description: All Good
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    type: object
                    properties:
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string
                      _id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      dob:
                        type: string
                        format: date
                      qualification:
                        type: string
                      aboutme:
                        type: string
                      phno:
                        type: number
                      role:
                        type: string
                      createdAt:
                        type: string
                        format: date
                      updatedAt:
                        type: string
                        format: date
                      __v:
                        type: number
        "422":
          description: Please Login first.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string

  /updateuser:
    patch:
      tags:
        - User Related Operations
      summary: Update User Details
      consumes:
        - application/json
      producers:
        - application/json
      requestBody:
        # required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                dob:
                  type: string
                  format: date
                qualification:
                  type: string
                aboutme:
                  type: string
                phno:
                  type: string
      responses:
        "200":
          description: All Good
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    type: object
                    properties:
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string
                      _id:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      dob:
                        type: string
                        format: date
                      qualification:
                        type: string
                      aboutme:
                        type: string
                      phno:
                        type: number
                      role:
                        type: string
                      createdAt:
                        type: string
                        format: date
                      updatedAt:
                        type: string
                        format: date
                      __v:
                        type: number

  /uploadphoto:
    patch:
      tags:
        - User Related Operations
      summary: User Can Signup using this path
      consumes:
        - application/json
      producers:
        - application/json
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
      responses:
        "200":
          description: All Good
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  photo:
                    type: object
                    properties:
                      id:
                        type: string
                      secure_url:
                        type: string
        "422":
          description: Unprocessable.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
